!------------------------------------------------------------------------

&tao_start
  plot_file = "tao_plot.init"
/

!------------------------------------------------------------------------

&tao_design_lattice
  n_universes = 1
  design_lattice(1) = "/home/bell/GIT_PROJECTS/Nuclotron/BMAD/lattices/var1.bmad"
  design_lattice(1)%dynamic_aperture_calc = True
/

!------------------------------------------------------------------------

&tao_params
  global%plot_on = T
/

&tao_dynamic_aperture
  da_param%min_angle = 0
  da_param%max_angle = 3.1415926  
  a_emit = 5e-6
  b_emit = 5e-6
  ellipse_scale = 10   ! Draw beam ellipse at 10 sigma
  pz = 0, 0.025, 0.1
  da_param%n_angle = 32
  da_param%n_turn = 200 ! This is set low for demonstration purposes.
  !da_param%abs_accuracy = 1e-5
  da_param%rel_accuracy = 1e-2
/
